apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wg-q613ja-python 
  janus-idp.io/tekton: wg-q613ja-python
  backstage.io/kubernetes-id: wg-q613ja-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wg-q613ja-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  